"""Initial migration3.

Revision ID: 3a43172a74c4
Revises: 2628a6f7ae73
Create Date: 2022-11-17 09:52:28.826542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a43172a74c4'
down_revision = '2628a6f7ae73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_code', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Client')
    # ### end Alembic commands ###
