"""Initial migration4.

Revision ID: 512ebbecb940
Revises: 643b657f663f
Create Date: 2022-11-15 10:06:06.679669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '512ebbecb940'
down_revision = '643b657f663f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Projects', schema=None) as batch_op:
        batch_op.alter_column('client_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('client_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('curr_end_date',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Projects', schema=None) as batch_op:
        batch_op.alter_column('curr_end_date',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('client_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('client_name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
