"""Initial migration4.

Revision ID: 643b657f663f
Revises: f693f5b092ba
Create Date: 2022-11-15 10:05:13.996803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '643b657f663f'
down_revision = 'f693f5b092ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Projects', schema=None) as batch_op:
        batch_op.alter_column('engagement_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('signing_entity',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('business_entity',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Projects', schema=None) as batch_op:
        batch_op.alter_column('business_entity',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('signing_entity',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('engagement_type',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
