"""Initial Dummy projects

Revision ID: a0859195e530
Revises: f62df6ecbe33
Create Date: 2022-11-18 14:33:02.983625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0859195e530'
down_revision = 'f62df6ecbe33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Dummy',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('client_code', sa.String(), nullable=True),
    sa.Column('curr_end_date', sa.String(), nullable=True),
    sa.Column('engagement_type', sa.String(), nullable=True),
    sa.Column('signing_entity', sa.String(), nullable=True),
    sa.Column('business_entity', sa.String(), nullable=True),
    sa.Column('engagement_number', sa.String(), nullable=True),
    sa.Column('country_one', sa.String(), nullable=False),
    sa.Column('country_two', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('capability', sa.String(), nullable=True),
    sa.Column('capability1', sa.String(), nullable=True),
    sa.Column('capability3', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Test')
    with op.batch_alter_table('Client', schema=None) as batch_op:
        batch_op.alter_column('client_code',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('client_name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Client', schema=None) as batch_op:
        batch_op.alter_column('client_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('client_code',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.create_table('Test',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Test_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('Opp_Name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Salesforce_ID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Stage', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Test_pkey')
    )
    op.drop_table('Dummy')
    # ### end Alembic commands ###
