"""Initial migration4.

Revision ID: bb0e56bad5a9
Revises: 
Create Date: 2022-11-15 10:02:08.211080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb0e56bad5a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('client_code', sa.String(), nullable=False),
    sa.Column('curr_end_date', sa.String(), nullable=False),
    sa.Column('engagement_type', sa.String(), nullable=False),
    sa.Column('signing_entity', sa.String(), nullable=False),
    sa.Column('business_entity', sa.String(), nullable=False),
    sa.Column('engagement_number', sa.String(), nullable=False),
    sa.Column('country_one', sa.String(), nullable=False),
    sa.Column('country_two', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('capability', sa.String(), nullable=False),
    sa.Column('capability1', sa.String(), nullable=True),
    sa.Column('capability3', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Salesforce',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Opp_Name', sa.String(), nullable=False),
    sa.Column('Salesforce_ID', sa.String(), nullable=False),
    sa.Column('Stage', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Tentative_Projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('project_start_date', sa.String(), nullable=False),
    sa.Column('project_end_date', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'project_id')
    )
    op.create_table('Test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Opp_Name', sa.String(), nullable=False),
    sa.Column('Salesforce_ID', sa.String(), nullable=False),
    sa.Column('Stage', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Test')
    op.drop_table('Tentative_Projects')
    op.drop_table('Salesforce')
    op.drop_table('Projects')
    # ### end Alembic commands ###
