"""Initial migration3.

Revision ID: c260f87a6c28
Revises: fed98a8471d3
Create Date: 2022-11-15 16:44:20.770789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c260f87a6c28'
down_revision = 'fed98a8471d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tentative_Projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_name', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tentative_Projects', schema=None) as batch_op:
        batch_op.drop_column('project_name')

    # ### end Alembic commands ###
