"""Initial migration3.

Revision ID: f62df6ecbe33
Revises: 3a43172a74c4
Create Date: 2022-11-17 09:54:20.946299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f62df6ecbe33'
down_revision = '3a43172a74c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_name', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Client', schema=None) as batch_op:
        batch_op.drop_column('client_name')

    # ### end Alembic commands ###
