"""Initial migration4.

Revision ID: f693f5b092ba
Revises: bb0e56bad5a9
Create Date: 2022-11-15 10:03:25.901093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f693f5b092ba'
down_revision = 'bb0e56bad5a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Projects', schema=None) as batch_op:
        batch_op.alter_column('engagement_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('country_one',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('capability',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Projects', schema=None) as batch_op:
        batch_op.alter_column('capability',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('country_one',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('engagement_number',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
