"""Initial migration3.

Revision ID: fed98a8471d3
Revises: 512ebbecb940
Create Date: 2022-11-15 16:38:15.292822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fed98a8471d3'
down_revision = '512ebbecb940'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tentative_Projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_type', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('client', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tentative_Projects', schema=None) as batch_op:
        batch_op.drop_column('client')
        batch_op.drop_column('project_type')

    # ### end Alembic commands ###
